### ISSUE TITLE
Following README.md, Unable to find image 'spanou/qemu-m4:latest' locally

### ISSUE THREAD

**Issue by embdevspec** [spanou/baremetal-super-minimal#2]
Was running `docker run -it --rm --privileged --name qemu-m4 --hostname=qemu-m4 --mount type=bind,source="$HOME"/development,target=/home/spanou/development spanou/qemu-m4:latest`  per instructions.

Assignees: embdevspec
Labels:

**Comment by embdevspec** [comment]
Seems harmless. Follow on stuff works.

**Comment by spanou** [comment]
Thanks for the note @embdevspec, much appreciated. 

Did you happen to get this the **_very first_** time you executed the pull command ?

**Comment by embdevspec** [comment]
@spanou ,  definitely on first time.  I have no idea what I was doing.  It appears to have only occurred on the first time as well.

**Comment by spanou** [comment]
Ok, that makes total sense. 

Effectively what is happening, is the very first time the actual docker image is not in your local "cache". Docker first looks to find a docker image in your local storage, if it doesn't find it, it then looks up on [hub.docker.com](https://hub.docker.com/) it parses the image id ```spanou/qemu-m4:latest``` looking for the user's repo [hub.docker.com/u/spanou](https://hub.docker.com/u/spanou), there it finds the image [hub.docker.com/u/spanou/qemu-m4](https://hub.docker.com/r/spanou/qemu-m4) and then from the list of tags for that image it downloads the [:latest](https://hub.docker.com/r/spanou/qemu-m4/tags). 

So since the it has found the image on the docker hub it will then download it on your local disk, from then on it will never go up on the docker hub unless I update the image with the tag latest. 

Thank you very much for pointing that out, I will put a comment in the documentation to allude to this sequence. I will not close this issue until the documentation has been updated. 

Thank you so much! 

Cheers,
Sakis

**Comment by spanou** [comment]
@embdevspec , I have resolved the issue by documenting the behavior in this commit https://github.com/spanou/baremetal-super-minimal/commit/69bcfd22572b2cdf46b52458e3f7e1b8476c8253. Let me know if that addresses your note. I'll close it afterwards.

**Comment by embdevspec** [comment]
Looks good to me.
